config/routes.rb
Textsearch::Application.routes.draw do
  resources :searches

  root :to => 'searches#index'

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @content=params[:search_text]
    ary = Array.new
    returnAry = Array.new
    if @content!=nil
      for i in 0..@content.length()
        for j in i..@content.length()
          if @content[i,j].length()>1 and !(ary.include?(@content[i,j]))
            ary.push(@content[i,j])
          end
        end
      end
    end

    file = File.new(Rails.public_path+"/dic.txt", "r")
    while (line = file.gets)
      if ary.include?(line.strip! || line)
        returnAry.push(line.strip! || line)
      end
    end
    file.close
    if(returnAry.length()!=0)
      @content = returnAry
    else
      @content = "No Matching"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textsearch</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/index.html.erb
<h1>Search Function. </h1>
<h3>My search works by following steps:</h3>
<ol>
	<li>Find all possible patterns in a string. Add this patterns to an array.</li>
	<li>Iterate the dictory.</li>
	<li>If current line in the dictory match any pattern in pattern array. Add it to the result String list.</li>
	<li>return the result list</li>
</ol>

<%= form_tag searches_path, :method => 'get' do %>
<%= text_field_tag :search_text, params[:search_text],:placeholder=>"saerch"%>
	<button id='submit' type="submit" class="btn-search" ><%=image_tag("search.png",:size => "16x18")%></button>
<% end %>

<div id='return' class='return'>
	<%=@content%>
</div>